# Figure 6. Parametric sweep: how the three tests behave on simulated data.
#
# This figure does not use real data. It uses data generated by the package's
# own simulator, where the true answer is known in advance, so the tests can be
# marked against it.
#
# In each simulated dataset some sites are given a real difference between
# conditions and the rest are given none. Two things are then measured:
#
#   False-positive rate  how often a test calls a site significant when no real
#                        difference was put there. This should stay near 0.05,
#                        which is the level the correction claims to hold.
#
#   Power                how often a test finds a difference that really is
#                        there. Higher is better, but only meaningful if the
#                        false-positive rate is under control.
#
# WHAT IS BEING VARIED ALONG THE HORIZONTAL AXIS
#
# Sigma controls how much samples differ from one another for reasons unrelated
# to the condition being studied, such as one donor simply editing more than
# another. It is the noise the random effect in the GLMM exists to absorb. Small
# sigma means samples behave alike, large sigma means they vary a lot.
#
# An earlier version of this figure described sigma as variation between sites.
# That was wrong. The simulator draws a value per sample, independently at each
# site, so it measures variation across samples, which is a different thing.
#
# WHY THE FIGURE IS SPLIT INTO COLUMNS BY SAMPLE SIZE
#
# The table this figure replaces averaged over sample size, and that average hid
# the main result. As the number of samples grows, false-positive rate and power
# move in opposite directions for Fisher compared with the GLMM. Splitting by
# sample size is the point of the figure, not decoration, so a reader can see
# that the ranking of the tests changes with the size of the experiment.
#
# READING IT
#
# Top row is false-positive rate, bottom row is power. Columns are 3, 6 and 10
# samples per group. Colour is the test. The dashed line at 0.05 appears only on
# the top row, because that is the level false positives are supposed to be held
# at, and there is no equivalent target for power.
#
# Wilcoxon is drawn in a full colour rather than the muted grey used for it in
# other figures. At 10 samples per group it reaches a power of 0.487, which is
# the one setting in this project where it demonstrably works, and greying it
# out would understate that.
#
# Input:  reditr_parametric_null.txt, produced by reditr_parametric_null.R
# Output: parametric_sweep_reditr.png

suppressPackageStartupMessages({ library(data.table); library(ggplot2) })
setwd("/rds/general/user/sj1825/home/msc_prj")

GLMM_C <- "#2a78d6"; FISH_C <- "#eb6834"; WILC_C <- "#7a4ea8"
SURF <- "#fcfcfb"; INK <- "#0b0b0b"; MUTED <- "#52514e"; GRIDS <- "#e1e0d9"

# One row per combination of sigma, sample size, random seed and test. Several
# seeds were run at every setting, so averaging over them here gives one point
# per line rather than a scatter of repeated runs.
#
# power_10 is power at the smallest of the planted effect sizes. It is the
# hardest to detect, so it is the fairest basis for comparing the tests.
p <- fread("reditr_parametric_null.txt")
d <- p[, .(fpr = mean(fpr), power = mean(power_10)), by = .(sigma, npc, test)]
d[, test := factor(c(GLMM = "GLMM", Fisher = "Fisher", Wilcox = "Wilcoxon")[test],
                   levels = c("GLMM", "Fisher", "Wilcoxon"))]

# Reshape so false-positive rate and power become two values of a single column.
# ggplot needs them stacked like this to put them on separate rows of the grid.
long <- melt(d, id.vars = c("sigma", "npc", "test"),
             measure.vars = c("fpr", "power"), variable.name = "metric", value.name = "y")

# Short labels for the row and column headings. Longer wording was cut off
# inside the heading strips, and the full definitions belong in the caption
# where there is room for them.
long[, metric := factor(fifelse(metric == "fpr", "False-positive rate", "Power"),
                        levels = c("False-positive rate", "Power"))]
long[, npc_lab := factor(paste0("n = ", npc, " per group"),
                         levels = paste0("n = ", c(3, 6, 10), " per group"))]

# The 0.05 reference line is put in its own small table so it appears on the
# false-positive row only. Drawn as a plain horizontal line it would repeat on
# the power row too, where it means nothing.
ref <- data.table(metric = factor("False-positive rate", levels = levels(long$metric)), yint = 0.05)

pl <- ggplot(long, aes(sigma, y, colour = test)) +
  geom_hline(data = ref, aes(yintercept = yint), linetype = "22",
             colour = MUTED, linewidth = 0.5, inherit.aes = FALSE) +
  geom_line(linewidth = 0.9) +
  geom_point(size = 2.4, stroke = 0) +
  facet_grid(metric ~ npc_lab, scales = "free_y", switch = "y") +
  scale_colour_manual(values = c(GLMM = GLMM_C, Fisher = FISH_C, Wilcoxon = WILC_C), name = NULL) +
  scale_x_continuous(breaks = c(0, 0.1, 0.25, 0.5, 1.0),
                     labels = c("0", "0.1", "0.25", "0.5", "1.0"),
                     expand = expansion(mult = c(0.04, 0.06))) +
  scale_y_continuous(labels = scales::number_format(accuracy = 0.01),
                     expand = expansion(mult = c(0.06, 0.12))) +
  labs(
    title = "reditR parametric sweep: calibration and power against between-sample variance",
    x = "Between-sample random-effect SD (sigma)", y = NULL) +
  theme_minimal(base_size = 12) +
  theme(
    # The subtitle has been removed from the figure and its content moved into
    # the written caption. The title is given a larger bottom margin to fill the
    # space it left.
    plot.title = element_text(face = "bold", size = 14.5, colour = INK,
                              margin = margin(b = 14)),
    strip.text.x = element_text(face = "bold", size = 11, colour = INK),
    strip.text.y.left = element_text(size = 10.5, colour = INK, angle = 90, face = "bold"),
    strip.placement = "outside",
    axis.title.x = element_text(size = 10, colour = MUTED, margin = margin(t = 8)),
    axis.text = element_text(size = 9, colour = MUTED),
    legend.position = "top", legend.justification = "left",
    legend.text = element_text(size = 10.5, colour = INK),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(colour = GRIDS, linewidth = 0.35),
    panel.spacing.x = unit(1.1, "lines"), panel.spacing.y = unit(1.3, "lines"),
    plot.background = element_rect(fill = SURF, colour = NA),
    plot.margin = margin(12, 16, 12, 12))

ggsave("parametric_sweep_reditr.png", pl, width = 12.5, height = 7.2, dpi = 300, bg = SURF)
cat("Written: parametric_sweep_reditr.png\n")
